import {
  mockAssignedToField,
  mockCancelReasonField,
  mockCompletedAtField,
  mockDescriptionField,
  mockDueDateField,
  mockEmailField,
  mockFavoriteField,
  mockMembersField,
  mockNameField,
  mockOwnersField,
  mockProjectField,
  mockProjectType,
  mockRoleField,
  mockStatusField,
  mockTagsField,
  mockTasksField,
  mockTaskType,
  mockTeamType,
  mockTitleField,
  mockUserType,
} from "./config.mock.ts";

import type { NodeSchema } from "./node.ts";

export const mockNodeSchema = {
  fields: {
    [mockNameField.key]: mockNameField,
    [mockTitleField.key]: mockTitleField,
    [mockDescriptionField.key]: mockDescriptionField,
    [mockStatusField.key]: mockStatusField,
    [mockAssignedToField.key]: mockAssignedToField,
    [mockOwnersField.key]: mockOwnersField,
    [mockMembersField.key]: mockMembersField,
    [mockTasksField.key]: mockTasksField,
    [mockTagsField.key]: mockTagsField,
    [mockDueDateField.key]: mockDueDateField,
    [mockEmailField.key]: mockEmailField,
    [mockProjectField.key]: mockProjectField,
    [mockFavoriteField.key]: mockFavoriteField,
    [mockRoleField.key]: mockRoleField,
    [mockCompletedAtField.key]: mockCompletedAtField,
    [mockCancelReasonField.key]: mockCancelReasonField,
  },
  types: {
    [mockTaskType.key]: mockTaskType,
    [mockProjectType.key]: mockProjectType,
    [mockUserType.key]: mockUserType,
    [mockTeamType.key]: mockTeamType,
  },
} as const satisfies NodeSchema;
