declare const GDRIVE_APP_DIR_NAME: string;
declare const GDRIVE_CLIENT_ID: string;
declare const GDRIVE_API_KEY: string;

const _GDRIVE_APP_DIR_NAME = GDRIVE_APP_DIR_NAME;
const _GDRIVE_CLIENT_ID = GDRIVE_CLIENT_ID;
const _GDRIVE_API_KEY = GDRIVE_API_KEY;

export { _GDRIVE_APP_DIR_NAME as GDRIVE_APP_DIR_NAME };
export { _GDRIVE_CLIENT_ID as GDRIVE_CLIENT_ID };
export { _GDRIVE_API_KEY as GDRIVE_API_KEY };